# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z30xoOBtaXSKOL7D6TfJk_qEbCGItcJo
"""

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("ozon4.csv",sep=";")
plt.style.use('ggplot')

data.head()



data.info()

data.describe()

plt.scatter(data['maxO3'],data['T12'])
plt.show()

y=data.iloc[:,2].values

y

del data['maxO3']

data.head()

x=data.iloc[:,:].values

x

print(x.shape)
print(y.shape)

if x.shape[0] != y.shape[0]:
  print("x and y rows are mismatched, check dataset again")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1.0/3)

x_train.shape

x_test.shape

regresseur=LinearRegression()
regresseur.fit(x_train,y_train)

y_pred= regresseur.predict(x_test)

y_pred

plt.plot(x_train,regresseur.predict(x_train),color='blue')